name: master
on:
  push:
    branches:
      - master
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Test with coverage
      run: |
        sbt clean coverage test
        sbt coverageReport

    - name: Sonar scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt -Dsonar.login=$SONAR_TOKEN sonarScan

    - name: Assemble
      run: sbt "clean; set test in assembly := {}; assembly"

    - name: Upload to the server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/scala-2.13/adjutant-assembly-0.1.jar
        remote: /tmp/${{ github.sha }}.jar
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}